-- Migration: Create voter_candidates junction table
-- This table stores the 5 candidates each voter votes for

CREATE TABLE IF NOT EXISTS public.voter_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voter_symbol VARCHAR(50) NOT NULL REFERENCES public.voters(voter_symbol) ON DELETE CASCADE,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    vote_order INTEGER NOT NULL CHECK (vote_order BETWEEN 1 AND 5),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(voter_symbol, vote_order)
);

-- Index for fast lookup by voter
CREATE INDEX IF NOT EXISTS idx_voter_candidates_voter ON public.voter_candidates(voter_symbol);

-- Index for fast lookup by candidate
CREATE INDEX IF NOT EXISTS idx_voter_candidates_candidate ON public.voter_candidates(candidate_id);

-- Enable RLS
ALTER TABLE public.voter_candidates ENABLE ROW LEVEL SECURITY;

-- RLS Policies (same as voters table)
CREATE POLICY "voter_candidates_select" ON public.voter_candidates
    FOR SELECT USING (true);

CREATE POLICY "voter_candidates_insert" ON public.voter_candidates
    FOR INSERT WITH CHECK (true);

CREATE POLICY "voter_candidates_delete" ON public.voter_candidates
    FOR DELETE USING (true);

CREATE POLICY "voter_candidates_update" ON public.voter_candidates
    FOR UPDATE USING (true);

-- Function to get candidates for a voter
CREATE OR REPLACE FUNCTION public.get_voter_candidates(p_voter_symbol VARCHAR)
RETURNS TABLE (
    vote_order INTEGER,
    candidate_id BIGINT,
    candidate_name VARCHAR,
    list_name VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        vc.vote_order,
        c.id AS candidate_id,
        c.candidate_name,
        el.list_name
    FROM public.voter_candidates vc
    JOIN public.candidates c ON c.id = vc.candidate_id
    JOIN public.electoral_lists el ON el.id = c.list_id
    WHERE vc.voter_symbol = p_voter_symbol
    ORDER BY vc.vote_order;
END;
$$ LANGUAGE plpgsql STABLE;
